version: "3"
services:
  webgrind:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - "8200:80"
    volumes:
      - ./:/app
#      - /path/to/xdebug/files:/tmp